server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Cấu hình routing cho SPA (Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Tối ưu hóa cache cho các tài nguyên tĩnh
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
